### ISSUE TITLE
ImportError: libMagnumBulletIntegration.so.2

### ISSUE THREAD

**Issue by DrJimFan** [alex-petrenko/megaverse#18]
I'm able to install the library successfully, but I get this error when I try to run the example command: 

```python
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/conda/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/user/.local/lib/python3.8/site-packages/megaverse_rl/train.py", line 11, in <module>
    from megaverse_rl.megaverse_utils import register_env
  File "/home/user/.local/lib/python3.8/site-packages/megaverse_rl/megaverse_utils.py", line 4, in <module>
    from megaverse.megaverse_env import MegaverseEnv, make_env_multitask
  File "/home/user/.local/lib/python3.8/site-packages/megaverse/megaverse_env.py", line 8, in <module>
    from megaverse.extension.megaverse import MegaverseGym, set_megaverse_log_level
ImportError: libMagnumBulletIntegration.so.2: cannot open shared object file: No such file or directory
```

I appreciate any help!

**Comment by xbz-24** [comment]
is there any fix for thsi, I am getting same bullshit
